Fix error on test due to missing sprockets-rails dependency
Fix the following error happening running `bundle exec rspec`:

```
An error occurred while loading rails_helper.
Failure/Error: Rails.application.initialize!

NoMethodError:
  undefined method `assets' for #<Rails::Application::Configuration:0x00000000007be8>
# ./spec/dummy/config/environment.rb:7:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `<top (required)>'
```